#================================================================
#  Copyright (C) 2022 noodles. All rights reserved.
#  
#  文件名称：Makefile
#  创 建 者：noodles
#  邮    箱：peizezhong@163.com
#  创建日期：2022年03月30日
#  描    述：
#  
#================================================================
.DEFAULT_GOAL = lib 

include ../../makeconfig

lib: $(BUILD_DIR) $(OBJ_FILES)
